// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: Popup_Screens

#include "../ui.h"

void ui_Attendance_screen_init(void)
{
    ui_Attendance = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Attendance, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AttendancePopup = lv_obj_create(ui_Attendance);
    lv_obj_set_width(ui_AttendancePopup, 280);
    lv_obj_set_height(ui_AttendancePopup, 180);
    lv_obj_set_align(ui_AttendancePopup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AttendancePopup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_AttendancePopup, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AttendancePopup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_AttendancePopup, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_AttendancePopup, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_AttendancePopup, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_AttendancePopup, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PopupSuccess = lv_label_create(ui_AttendancePopup);
    lv_obj_set_width(ui_PopupSuccess, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PopupSuccess, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PopupSuccess, 0);
    lv_obj_set_y(ui_PopupSuccess, -15);
    lv_obj_set_align(ui_PopupSuccess, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PopupSuccess, "Attendance Successfully");
    lv_obj_set_style_text_color(ui_PopupSuccess, lv_color_hex(0x00A00B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PopupSuccess, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PopupSuccess, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CheckinTime = lv_label_create(ui_AttendancePopup);
    lv_obj_set_width(ui_CheckinTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckinTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckinTime, 0);
    lv_obj_set_y(ui_CheckinTime, 15);
    lv_obj_set_align(ui_CheckinTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CheckinTime, "Time");
    lv_obj_set_style_text_color(ui_CheckinTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CheckinTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}
