// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: Popup_Screens

#include "../ui.h"

void ui_ExpirePopup_screen_init(void)
{
    ui_ExpirePopup = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ExpirePopup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AttendancePopup4 = lv_obj_create(ui_ExpirePopup);
    lv_obj_set_width(ui_AttendancePopup4, 280);
    lv_obj_set_height(ui_AttendancePopup4, 180);
    lv_obj_set_align(ui_AttendancePopup4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AttendancePopup4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_AttendancePopup4, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AttendancePopup4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_AttendancePopup4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_AttendancePopup4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_AttendancePopup4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_AttendancePopup4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PopupSuccess4 = lv_label_create(ui_AttendancePopup4);
    lv_obj_set_width(ui_PopupSuccess4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PopupSuccess4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PopupSuccess4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PopupSuccess4, "Timeout");
    lv_obj_set_style_text_color(ui_PopupSuccess4, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PopupSuccess4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PopupSuccess4, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

}
