// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: Popup_Screens

#include "../ui.h"

void ui_FaceIDPopup_screen_init(void)
{
    ui_FaceIDPopup = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_FaceIDPopup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AttendancePopup2 = lv_obj_create(ui_FaceIDPopup);
    lv_obj_set_width(ui_AttendancePopup2, 280);
    lv_obj_set_height(ui_AttendancePopup2, 180);
    lv_obj_set_align(ui_AttendancePopup2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AttendancePopup2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_AttendancePopup2, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AttendancePopup2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_AttendancePopup2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_AttendancePopup2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_AttendancePopup2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_AttendancePopup2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PopupSuccess2 = lv_label_create(ui_AttendancePopup2);
    lv_obj_set_width(ui_PopupSuccess2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PopupSuccess2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PopupSuccess2, 0);
    lv_obj_set_y(ui_PopupSuccess2, -15);
    lv_obj_set_align(ui_PopupSuccess2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PopupSuccess2, "FaceID Enroll Successfully");
    lv_obj_set_style_text_color(ui_PopupSuccess2, lv_color_hex(0x00A00B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PopupSuccess2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PopupSuccess2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IDTextFaceID = lv_label_create(ui_AttendancePopup2);
    lv_obj_set_width(ui_IDTextFaceID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IDTextFaceID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IDTextFaceID, 0);
    lv_obj_set_y(ui_IDTextFaceID, 15);
    lv_obj_set_align(ui_IDTextFaceID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IDTextFaceID, "ID: ");
    lv_obj_set_style_text_color(ui_IDTextFaceID, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IDTextFaceID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}
