// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT POPUPMenuPanel

lv_obj_t * ui_POPUPMenuPanel_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_POPUPMenuPanel;
    cui_POPUPMenuPanel = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_POPUPMenuPanel, 280);
    lv_obj_set_height(cui_POPUPMenuPanel, 180);
    lv_obj_set_align(cui_POPUPMenuPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_POPUPMenuPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(cui_POPUPMenuPanel, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(cui_POPUPMenuPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(cui_POPUPMenuPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(cui_POPUPMenuPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(cui_POPUPMenuPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(cui_POPUPMenuPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_POPUPMENUPANEL_NUM);
    children[UI_COMP_POPUPMENUPANEL_POPUPMENUPANEL] = cui_POPUPMenuPanel;
    lv_obj_add_event_cb(cui_POPUPMenuPanel, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_POPUPMenuPanel, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_POPUPMenuPanel_create_hook(cui_POPUPMenuPanel);
    return cui_POPUPMenuPanel;
}

