// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT POPUPHome

lv_obj_t * ui_POPUPHome_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_POPUPHome;
    cui_POPUPHome = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_POPUPHome, 280);
    lv_obj_set_height(cui_POPUPHome, 180);
    lv_obj_set_align(cui_POPUPHome, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_POPUPHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(cui_POPUPHome, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(cui_POPUPHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(cui_POPUPHome, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(cui_POPUPHome, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(cui_POPUPHome, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(cui_POPUPHome, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label1;
    cui_Label1 = lv_label_create(cui_POPUPHome);
    lv_obj_set_width(cui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label1, LV_ALIGN_CENTER);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_POPUPHOME_NUM);
    children[UI_COMP_POPUPHOME_POPUPHOME] = cui_POPUPHome;
    children[UI_COMP_POPUPHOME_LABEL1] = cui_Label1;
    lv_obj_add_event_cb(cui_POPUPHome, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_POPUPHome, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_POPUPHome_create_hook(cui_POPUPHome);
    return cui_POPUPHome;
}

