// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_POPUPMENUPANEL_H
#define _UI_COMP_POPUPMENUPANEL_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT POPUPMenuPanel
#define UI_COMP_POPUPMENUPANEL_POPUPMENUPANEL 0
#define _UI_COMP_POPUPMENUPANEL_NUM 1
lv_obj_t * ui_POPUPMenuPanel_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
