// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: Popup_Screens

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Attendance
void ui_Attendance_screen_init(void);
lv_obj_t * ui_Attendance;
lv_obj_t * ui_AttendancePopup;
lv_obj_t * ui_PopupSuccess;
lv_obj_t * ui_CheckinTime;
// CUSTOM VARIABLES

// SCREEN: ui_Enroll
void ui_Enroll_screen_init(void);
lv_obj_t * ui_Enroll;
lv_obj_t * ui_EnrollPopup;
lv_obj_t * ui_StartingEnroll;
lv_obj_t * ui_SelectedID;
lv_obj_t * ui_ESCPanel;
lv_obj_t * ui_ESCButton2;
lv_obj_t * ui_AuthenticatePanel;
lv_obj_t * ui_AuthenticateButton;
// CUSTOM VARIABLES

// SCREEN: ui_Authenticate
void ui_Authenticate_screen_init(void);
lv_obj_t * ui_Authenticate;
lv_obj_t * ui_AttendancePopup1;
lv_obj_t * ui_PopupSuccess1;
lv_obj_t * ui_LoadingText;
// CUSTOM VARIABLES

// SCREEN: ui_FaceIDPopup
void ui_FaceIDPopup_screen_init(void);
lv_obj_t * ui_FaceIDPopup;
lv_obj_t * ui_AttendancePopup2;
lv_obj_t * ui_PopupSuccess2;
lv_obj_t * ui_IDTextFaceID;
// CUSTOM VARIABLES

// SCREEN: ui_FingerPopup
void ui_FingerPopup_screen_init(void);
lv_obj_t * ui_FingerPopup;
lv_obj_t * ui_AttendancePopup3;
lv_obj_t * ui_PopupSuccess3;
lv_obj_t * ui_IDTextFinger;
// CUSTOM VARIABLES

// SCREEN: ui_ExpirePopup
void ui_ExpirePopup_screen_init(void);
lv_obj_t * ui_ExpirePopup;
lv_obj_t * ui_AttendancePopup4;
lv_obj_t * ui_PopupSuccess4;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Attendance_screen_init();
    ui_Enroll_screen_init();
    ui_Authenticate_screen_init();
    ui_FaceIDPopup_screen_init();
    ui_FingerPopup_screen_init();
    ui_ExpirePopup_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Attendance);
}
