// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: Popup_Screens

#ifndef _POPUP_SCREENS_UI_H
#define _POPUP_SCREENS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Attendance
void ui_Attendance_screen_init(void);
extern lv_obj_t * ui_Attendance;
extern lv_obj_t * ui_AttendancePopup;
extern lv_obj_t * ui_PopupSuccess;
extern lv_obj_t * ui_CheckinTime;
// CUSTOM VARIABLES

// SCREEN: ui_Enroll
void ui_Enroll_screen_init(void);
extern lv_obj_t * ui_Enroll;
extern lv_obj_t * ui_EnrollPopup;
extern lv_obj_t * ui_StartingEnroll;
extern lv_obj_t * ui_SelectedID;
extern lv_obj_t * ui_ESCPanel;
extern lv_obj_t * ui_ESCButton2;
extern lv_obj_t * ui_AuthenticatePanel;
extern lv_obj_t * ui_AuthenticateButton;
// CUSTOM VARIABLES

// SCREEN: ui_Authenticate
void ui_Authenticate_screen_init(void);
extern lv_obj_t * ui_Authenticate;
extern lv_obj_t * ui_AttendancePopup1;
extern lv_obj_t * ui_PopupSuccess1;
extern lv_obj_t * ui_LoadingText;
// CUSTOM VARIABLES

// SCREEN: ui_FaceIDPopup
void ui_FaceIDPopup_screen_init(void);
extern lv_obj_t * ui_FaceIDPopup;
extern lv_obj_t * ui_AttendancePopup2;
extern lv_obj_t * ui_PopupSuccess2;
extern lv_obj_t * ui_IDTextFaceID;
// CUSTOM VARIABLES

// SCREEN: ui_FingerPopup
void ui_FingerPopup_screen_init(void);
extern lv_obj_t * ui_FingerPopup;
extern lv_obj_t * ui_AttendancePopup3;
extern lv_obj_t * ui_PopupSuccess3;
extern lv_obj_t * ui_IDTextFinger;
// CUSTOM VARIABLES

// SCREEN: ui_ExpirePopup
void ui_ExpirePopup_screen_init(void);
extern lv_obj_t * ui_ExpirePopup;
extern lv_obj_t * ui_AttendancePopup4;
extern lv_obj_t * ui_PopupSuccess4;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
