version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data

  ui:
    build: .
    container_name: ui
    command: python ui.py
    ports:
      - "8000:8000"
    env_file: .env
    volumes: 
      - ./logs:/app/logs
    depends_on:
      - redis

  listener:
    build: .
    container_name: listener
    command: python listener.py
    env_file: .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis

  processor:
    build: .
    container_name: processor
    command: python processor.py
    env_file: .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis
      
  nanomq:
    image: emqx/nanomq:0.18.2-full
    container_name: nanomq
    ports:
      - "1883:1883"
    
volumes:
  redis-data:

