// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Authenticate_screen_init(void)
{
    ui_Authenticate = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Authenticate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Authenticate, ui_event_Authenticate, LV_EVENT_ALL, NULL);

}
