// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Enroll_screen_init(void)
{
    ui_Enroll = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Enroll, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Enroll, ui_event_Enroll, LV_EVENT_ALL, NULL);

}
