// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_FingerEnroll_screen_init(void)
{
    ui_FingerEnroll = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_FingerEnroll, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
