// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeText = lv_label_create(ui_Home);
    lv_obj_set_width(ui_HomeText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeText, 0);
    lv_obj_set_y(ui_HomeText, -105);
    lv_obj_set_align(ui_HomeText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeText, "Home");
    lv_obj_set_style_text_color(ui_HomeText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeText, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POPUPHomePanel = lv_obj_create(ui_Home);
    lv_obj_set_width(ui_POPUPHomePanel, 280);
    lv_obj_set_height(ui_POPUPHomePanel, 180);
    lv_obj_set_align(ui_POPUPHomePanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_POPUPHomePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_POPUPHomePanel, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_POPUPHomePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_POPUPHomePanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_POPUPHomePanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_POPUPHomePanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_POPUPHomePanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeTime = lv_label_create(ui_POPUPHomePanel);
    lv_obj_set_width(ui_HomeTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HomeTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeTime, "11:00");
    lv_obj_set_style_text_color(ui_HomeTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeTime, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeDay = lv_label_create(ui_Home);
    lv_obj_set_width(ui_HomeDay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeDay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeDay, 23);
    lv_obj_set_y(ui_HomeDay, 108);
    lv_obj_set_align(ui_HomeDay, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_HomeDay, "21-10-2024");
    lv_obj_set_style_text_color(ui_HomeDay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeDay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeDay, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeDate = lv_label_create(ui_Home);
    lv_obj_set_width(ui_HomeDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeDate, -23);
    lv_obj_set_y(ui_HomeDate, 108);
    lv_obj_set_align(ui_HomeDate, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_HomeDate, "Monday");
    lv_obj_set_style_text_color(ui_HomeDate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeDate, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonHomeToMenu = lv_btn_create(ui_Home);
    lv_obj_set_width(ui_ButtonHomeToMenu, 12);
    lv_obj_set_height(ui_ButtonHomeToMenu, 50);
    lv_obj_set_x(ui_ButtonHomeToMenu, 150);
    lv_obj_set_y(ui_ButtonHomeToMenu, 1);
    lv_obj_set_align(ui_ButtonHomeToMenu, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ButtonHomeToMenu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonHomeToMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonHomeToMenu, &ui_img_1101766569, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonHomeToMenu, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonHomeToMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ButtonHomeToMenu, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ButtonHomeToMenu, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ButtonHomeToMenu, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ButtonHomeToMenu, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageWifi = lv_img_create(ui_Home);
    lv_img_set_src(ui_ImageWifi, &ui_img_1052123464);
    lv_obj_set_width(ui_ImageWifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageWifi, -23);
    lv_obj_set_y(ui_ImageWifi, -105);
    lv_obj_set_align(ui_ImageWifi, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_ImageWifi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageBluetooth = lv_img_create(ui_Home);
    lv_img_set_src(ui_ImageBluetooth, &ui_img_694049672);
    lv_obj_set_width(ui_ImageBluetooth, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageBluetooth, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageBluetooth, 99);
    lv_obj_set_y(ui_ImageBluetooth, -105);
    lv_obj_set_align(ui_ImageBluetooth, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBluetooth, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageBluetooth, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageSDCard = lv_img_create(ui_Home);
    lv_img_set_src(ui_ImageSDCard, &ui_img_988180266);
    lv_obj_set_width(ui_ImageSDCard, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageSDCard, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageSDCard, 70);
    lv_obj_set_y(ui_ImageSDCard, -105);
    lv_obj_set_align(ui_ImageSDCard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageSDCard, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSDCard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageWifiDisconnect = lv_img_create(ui_Home);
    lv_img_set_src(ui_ImageWifiDisconnect, &ui_img_1985633929);
    lv_obj_set_width(ui_ImageWifiDisconnect, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWifiDisconnect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageWifiDisconnect, 43);
    lv_obj_set_y(ui_ImageWifiDisconnect, -105);
    lv_obj_set_align(ui_ImageWifiDisconnect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWifiDisconnect, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWifiDisconnect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ButtonHomeToMenu, ui_event_ButtonHomeToMenu, LV_EVENT_ALL, NULL);

}
