// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: access_control

#include "../ui.h"
#include "esp_camera.h"

static lv_obj_t *camera_canvas = NULL;

static void camera_timer_cb(lv_timer_t *timer);

void
ui_Screen1_screen_init (void)
{
  ui_Screen1 = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);
  camera_canvas = lv_canvas_create(ui_Screen1);
  lv_timer_create(camera_timer_cb, 33, NULL);
}

static void
camera_timer_cb (lv_timer_t *timer)
{
  camera_fb_t *fb = esp_camera_fb_get();
  if (!fb)
  {
    return;
  }

  lv_canvas_set_buffer(
      camera_canvas, fb->buf, fb->width, fb->height, LV_IMG_CF_TRUE_COLOR);

  lv_obj_invalidate(camera_canvas);

  esp_camera_fb_return(fb);
}
