// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_UserData_screen_init(void)
{
    ui_UserData = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_UserData, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel4 = lv_obj_create(ui_UserData);
    lv_obj_set_width(ui_Panel4, 280);   
    lv_obj_set_height(ui_Panel4, 160);
    lv_obj_set_x(ui_Panel4, 0);
    lv_obj_set_y(ui_Panel4, 5);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel4, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Panel4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Panel4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UserID1 = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_UserID1, 308);
    lv_obj_set_height(ui_UserID1, 20);
    lv_obj_set_x(ui_UserID1, -68);
    lv_obj_set_y(ui_UserID1, 93);
    lv_obj_set_align(ui_UserID1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_UserID1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_UserID1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UserID1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_UserID1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ID1 = lv_label_create(ui_UserID1);
    lv_obj_set_width(ui_ID1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ID1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ID1, -10);
    lv_obj_set_y(ui_ID1, 0);
    lv_obj_set_align(ui_ID1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ID1, "1");
    lv_obj_set_style_text_color(ui_ID1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ID1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ID1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Name1 = lv_label_create(ui_UserID1);
    lv_obj_set_width(ui_Name1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Name1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Name1, 90);
    lv_obj_set_y(ui_Name1, 0);
    lv_obj_set_align(ui_Name1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Name1, "Dong Thanh Khoa");
    lv_obj_set_style_text_color(ui_Name1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Name1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Name1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UserID2 = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_UserID2, 308);
    lv_obj_set_height(ui_UserID2, 20);
    lv_obj_set_x(ui_UserID2, -68);
    lv_obj_set_y(ui_UserID2, 93);
    lv_obj_set_align(ui_UserID2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_UserID2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_UserID2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UserID2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_UserID2, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ID2 = lv_label_create(ui_UserID2);
    lv_obj_set_width(ui_ID2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ID2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ID2, -10);
    lv_obj_set_y(ui_ID2, 0);
    lv_obj_set_align(ui_ID2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ID2, "2");
    lv_obj_set_style_text_color(ui_ID2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ID2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ID2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Name2 = lv_label_create(ui_UserID2);
    lv_obj_set_width(ui_Name2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Name2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Name2, 90);
    lv_obj_set_y(ui_Name2, 0);
    lv_obj_set_align(ui_Name2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Name2, "Dong Thanh Khoa");
    lv_obj_set_style_text_color(ui_Name2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Name2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Name2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UserID3 = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_UserID3, 308);
    lv_obj_set_height(ui_UserID3, 20);
    lv_obj_set_x(ui_UserID3, -68);
    lv_obj_set_y(ui_UserID3, 93);
    lv_obj_set_align(ui_UserID3, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_UserID3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_UserID3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UserID3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_UserID3, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ID3 = lv_label_create(ui_UserID3);
    lv_obj_set_width(ui_ID3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ID3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ID3, -10);
    lv_obj_set_y(ui_ID3, 0);
    lv_obj_set_align(ui_ID3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ID3, "3");
    lv_obj_set_style_text_color(ui_ID3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ID3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ID3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Name3 = lv_label_create(ui_UserID3);
    lv_obj_set_width(ui_Name3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Name3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Name3, 90);
    lv_obj_set_y(ui_Name3, 0);
    lv_obj_set_align(ui_Name3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Name3, "Dong Thanh Khoa");
    lv_obj_set_style_text_color(ui_Name3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Name3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Name3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UserID4 = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_UserID4, 308);
    lv_obj_set_height(ui_UserID4, 20);
    lv_obj_set_x(ui_UserID4, -68);
    lv_obj_set_y(ui_UserID4, 93);
    lv_obj_set_align(ui_UserID4, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_UserID4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_UserID4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UserID4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_UserID4, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ID4 = lv_label_create(ui_UserID4);
    lv_obj_set_width(ui_ID4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ID4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ID4, -10);
    lv_obj_set_y(ui_ID4, 0);
    lv_obj_set_align(ui_ID4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ID4, "4");
    lv_obj_set_style_text_color(ui_ID4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ID4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ID4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Name4 = lv_label_create(ui_UserID4);
    lv_obj_set_width(ui_Name4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Name4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Name4, 90);
    lv_obj_set_y(ui_Name4, 0);
    lv_obj_set_align(ui_Name4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Name4, "Dong Thanh Khoa");
    lv_obj_set_style_text_color(ui_Name4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Name4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Name4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UserID5 = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_UserID5, 308);
    lv_obj_set_height(ui_UserID5, 20);
    lv_obj_set_x(ui_UserID5, -68);
    lv_obj_set_y(ui_UserID5, 93);
    lv_obj_set_align(ui_UserID5, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_UserID5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_UserID5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UserID5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_UserID5, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ID5 = lv_label_create(ui_UserID5);
    lv_obj_set_width(ui_ID5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ID5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ID5, -10);
    lv_obj_set_y(ui_ID5, 0);
    lv_obj_set_align(ui_ID5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ID5, "5");
    lv_obj_set_style_text_color(ui_ID5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ID5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ID5, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Name5 = lv_label_create(ui_UserID5);
    lv_obj_set_width(ui_Name5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Name5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Name5, 90);
    lv_obj_set_y(ui_Name5, 0);
    lv_obj_set_align(ui_Name5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Name5, "Dong Thanh Khoa");
    lv_obj_set_style_text_color(ui_Name5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Name5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Name5, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UserID6 = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_UserID6, 308);
    lv_obj_set_height(ui_UserID6, 20);
    lv_obj_set_x(ui_UserID6, -68);
    lv_obj_set_y(ui_UserID6, 93);
    lv_obj_set_align(ui_UserID6, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_UserID6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_UserID6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UserID6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_UserID6, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ID6 = lv_label_create(ui_UserID6);
    lv_obj_set_width(ui_ID6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ID6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ID6, -10);
    lv_obj_set_y(ui_ID6, 0);
    lv_obj_set_align(ui_ID6, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ID6, "6");
    lv_obj_set_style_text_color(ui_ID6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ID6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ID6, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Name6 = lv_label_create(ui_UserID6);
    lv_obj_set_width(ui_Name6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Name6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Name6, 90);
    lv_obj_set_y(ui_Name6, 0);
    lv_obj_set_align(ui_Name6, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Name6, "Dong Thanh Khoa");
    lv_obj_set_style_text_color(ui_Name6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Name6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Name6, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UserID7 = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_UserID7, 308);
    lv_obj_set_height(ui_UserID7, 20);
    lv_obj_set_x(ui_UserID7, -68);
    lv_obj_set_y(ui_UserID7, 93);
    lv_obj_set_align(ui_UserID7, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_UserID7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_UserID7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UserID7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_UserID7, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ID7 = lv_label_create(ui_UserID7);
    lv_obj_set_width(ui_ID7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ID7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ID7, -10);
    lv_obj_set_y(ui_ID7, 0);
    lv_obj_set_align(ui_ID7, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ID7, "7");
    lv_obj_set_style_text_color(ui_ID7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ID7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ID7, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Name7 = lv_label_create(ui_UserID7);
    lv_obj_set_width(ui_Name7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Name7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Name7, 90);
    lv_obj_set_y(ui_Name7, 0);
    lv_obj_set_align(ui_Name7, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Name7, "Dong Thanh Khoa");
    lv_obj_set_style_text_color(ui_Name7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Name7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Name7, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UserID8 = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_UserID8, 308);
    lv_obj_set_height(ui_UserID8, 20);
    lv_obj_set_x(ui_UserID8, -68);
    lv_obj_set_y(ui_UserID8, 93);
    lv_obj_set_align(ui_UserID8, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_UserID8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_UserID8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UserID8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_UserID8, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ID8 = lv_label_create(ui_UserID8);
    lv_obj_set_width(ui_ID8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ID8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ID8, -10);
    lv_obj_set_y(ui_ID8, 0);
    lv_obj_set_align(ui_ID8, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ID8, "8");
    lv_obj_set_style_text_color(ui_ID8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ID8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ID8, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Name8 = lv_label_create(ui_UserID8);
    lv_obj_set_width(ui_Name8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Name8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Name8, 90);
    lv_obj_set_y(ui_Name8, 0);
    lv_obj_set_align(ui_Name8, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Name8, "Dong Thanh Khoa");
    lv_obj_set_style_text_color(ui_Name8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Name8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Name8, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_UserData);
    lv_obj_set_width(ui_Panel5, 280);
    lv_obj_set_height(ui_Panel5, 23);
    lv_obj_set_x(ui_Panel5, 0);
    lv_obj_set_y(ui_Panel5, -95);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel5, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Panel5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Panel5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IDTextUserData = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_IDTextUserData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IDTextUserData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IDTextUserData, -5);
    lv_obj_set_y(ui_IDTextUserData, 0);
    lv_obj_set_align(ui_IDTextUserData, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_IDTextUserData, "ID");

    ui_NameTextUserData = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_NameTextUserData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NameTextUserData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NameTextUserData, 45);
    lv_obj_set_y(ui_NameTextUserData, 0);
    lv_obj_set_align(ui_NameTextUserData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NameTextUserData, "Name");
    lv_obj_set_style_text_font(ui_NameTextUserData, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ESCButton1 = lv_btn_create(ui_UserData);
    lv_obj_set_width(ui_ESCButton1, 50);
    lv_obj_set_height(ui_ESCButton1, 20);
    lv_obj_set_x(ui_ESCButton1, 23);
    lv_obj_set_y(ui_ESCButton1, 106);
    lv_obj_set_align(ui_ESCButton1, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_ESCButton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ESCButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ESCButton1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ESCButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ESCButton1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ESCButton1, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ESCButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ESCButton1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ESCButton1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ESCButton1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ESCButton1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ESCButton1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ESCText2 = lv_label_create(ui_ESCButton1);
    lv_obj_set_width(ui_ESCText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ESCText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ESCText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ESCText2, "ESC");
    lv_obj_set_style_text_color(ui_ESCText2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ESCText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ESCText2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_UserID1, ui_event_UserID1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_UserID2, ui_event_UserID2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_UserID3, ui_event_UserID3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_UserID4, ui_event_UserID4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_UserID5, ui_event_UserID5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_UserID6, ui_event_UserID6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_UserID7, ui_event_UserID7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_UserID8, ui_event_UserID8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ESCButton1, ui_event_ESCButton1, LV_EVENT_ALL, NULL);

}
