// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_UserInfo_screen_init(void)
{
    ui_UserInfo = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_UserInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_POPUPMenuPanel3 = lv_obj_create(ui_UserInfo);
    lv_obj_set_width(ui_POPUPMenuPanel3, 280);
    lv_obj_set_height(ui_POPUPMenuPanel3, 180);
    lv_obj_set_align(ui_POPUPMenuPanel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_POPUPMenuPanel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_POPUPMenuPanel3, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_POPUPMenuPanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_POPUPMenuPanel3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_POPUPMenuPanel3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_POPUPMenuPanel3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_POPUPMenuPanel3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IDTextEnroll = lv_label_create(ui_UserInfo);
    lv_obj_set_width(ui_IDTextEnroll, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IDTextEnroll, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IDTextEnroll, 28);
    lv_obj_set_y(ui_IDTextEnroll, -74);
    lv_obj_set_align(ui_IDTextEnroll, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_IDTextEnroll, "ID:");
    lv_obj_set_style_text_color(ui_IDTextEnroll, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IDTextEnroll, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NumberID = lv_label_create(ui_UserInfo);
    lv_obj_set_width(ui_NumberID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NumberID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NumberID, -109);
    lv_obj_set_y(ui_NumberID, -74);
    lv_obj_set_align(ui_NumberID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NumberID, "1");
    lv_obj_set_style_text_color(ui_NumberID, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NumberID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IDTextEnroll2 = lv_label_create(ui_UserInfo);
    lv_obj_set_width(ui_IDTextEnroll2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IDTextEnroll2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IDTextEnroll2, -25);
    lv_obj_set_y(ui_IDTextEnroll2, -75);
    lv_obj_set_align(ui_IDTextEnroll2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_IDTextEnroll2, "Ho Le Quoc Thang");
    lv_obj_set_style_text_color(ui_IDTextEnroll2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IDTextEnroll2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_UserInfo);
    lv_obj_set_width(ui_Panel1, 261);
    lv_obj_set_height(ui_Panel1, 27);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, -42);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_UserInfo);
    lv_obj_set_width(ui_Panel3, 261);
    lv_obj_set_height(ui_Panel3, 27);
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, -5);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Finger = lv_label_create(ui_UserInfo);
    lv_obj_set_width(ui_Finger, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Finger, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Finger, 34);
    lv_obj_set_y(ui_Finger, -41);
    lv_obj_set_align(ui_Finger, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Finger, "Finger");
    lv_obj_set_style_text_color(ui_Finger, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Finger, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FaceID = lv_label_create(ui_UserInfo);
    lv_obj_set_width(ui_FaceID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FaceID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FaceID, 34);
    lv_obj_set_y(ui_FaceID, -4);
    lv_obj_set_align(ui_FaceID, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_FaceID, "FaceID");
    lv_obj_set_style_text_color(ui_FaceID, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FaceID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FingerCheck = lv_label_create(ui_UserInfo);
    lv_obj_set_width(ui_FingerCheck, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FingerCheck, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FingerCheck, -35);
    lv_obj_set_y(ui_FingerCheck, -41);
    lv_obj_set_align(ui_FingerCheck, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_FingerCheck, "0/1");
    lv_obj_set_style_text_color(ui_FingerCheck, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FingerCheck, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FaceIDCheck = lv_label_create(ui_UserInfo);
    lv_obj_set_width(ui_FaceIDCheck, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FaceIDCheck, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FaceIDCheck, -35);
    lv_obj_set_y(ui_FaceIDCheck, -4);
    lv_obj_set_align(ui_FaceIDCheck, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_FaceIDCheck, "0/1");
    lv_obj_set_style_text_color(ui_FaceIDCheck, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FaceIDCheck, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EnrollFingerButton = lv_btn_create(ui_UserInfo);
    lv_obj_set_width(ui_EnrollFingerButton, 100);
    lv_obj_set_height(ui_EnrollFingerButton, 20);
    lv_obj_set_x(ui_EnrollFingerButton, -3);
    lv_obj_set_y(ui_EnrollFingerButton, 33);
    lv_obj_set_align(ui_EnrollFingerButton, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_EnrollFingerButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EnrollFingerButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_EnrollFingerButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_EnrollFingerButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_EnrollFingerButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_EnrollFingerButton, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_EnrollFingerButton);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Enroll Finger");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EnrollFaceIDButton = lv_btn_create(ui_UserInfo);
    lv_obj_set_width(ui_EnrollFaceIDButton, 100);
    lv_obj_set_height(ui_EnrollFaceIDButton, 20);
    lv_obj_set_x(ui_EnrollFaceIDButton, -3);
    lv_obj_set_y(ui_EnrollFaceIDButton, 64);
    lv_obj_set_align(ui_EnrollFaceIDButton, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_EnrollFaceIDButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EnrollFaceIDButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_EnrollFaceIDButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_EnrollFaceIDButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_EnrollFaceIDButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_EnrollFaceIDButton);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Enroll FaceID");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UserInfoText = lv_label_create(ui_UserInfo);
    lv_obj_set_width(ui_UserInfoText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UserInfoText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UserInfoText, 0);
    lv_obj_set_y(ui_UserInfoText, -105);
    lv_obj_set_align(ui_UserInfoText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UserInfoText, "User Info");
    lv_obj_set_style_text_color(ui_UserInfoText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_UserInfoText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UserInfoText, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UserInfoTime = lv_label_create(ui_UserInfo);
    lv_obj_set_width(ui_UserInfoTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UserInfoTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UserInfoTime, 23);
    lv_obj_set_y(ui_UserInfoTime, -105);
    lv_obj_set_align(ui_UserInfoTime, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_UserInfoTime, "Time");
    lv_obj_set_style_text_color(ui_UserInfoTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_UserInfoTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UserInfoTime, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ESCButton = lv_btn_create(ui_UserInfo);
    lv_obj_set_width(ui_ESCButton, 50);
    lv_obj_set_height(ui_ESCButton, 20);
    lv_obj_set_x(ui_ESCButton, 23);
    lv_obj_set_y(ui_ESCButton, 106);
    lv_obj_set_align(ui_ESCButton, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_ESCButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ESCButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ESCButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ESCButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ESCButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ESCButton, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ESCButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ESCButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ESCButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ESCButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ESCButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ESCButton, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ESCText = lv_label_create(ui_ESCButton);
    lv_obj_set_width(ui_ESCText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ESCText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ESCText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ESCText, "ESC");
    lv_obj_set_style_text_color(ui_ESCText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ESCText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ESCText, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeButton = lv_btn_create(ui_UserInfo);
    lv_obj_set_width(ui_HomeButton, 50);
    lv_obj_set_height(ui_HomeButton, 20);
    lv_obj_set_x(ui_HomeButton, -23);
    lv_obj_set_y(ui_HomeButton, 106);
    lv_obj_set_align(ui_HomeButton, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_bg_color(ui_HomeButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HomeButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HomeButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HomeButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_HomeButton, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_HomeButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_HomeButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_HomeButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_HomeButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_HomeButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeButton, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeText1 = lv_label_create(ui_HomeButton);
    lv_obj_set_width(ui_HomeText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HomeText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeText1, "Home");
    lv_obj_set_style_text_color(ui_HomeText1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeText1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_EnrollFingerButton, ui_event_EnrollFingerButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_EnrollFaceIDButton, ui_event_EnrollFaceIDButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ESCButton, ui_event_ESCButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeButton, ui_event_HomeButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_UserInfo, ui_event_UserInfo, LV_EVENT_ALL, NULL);

}
