// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: Popup_Screens

#include "../ui.h"

void ui_Authenticate_screen_init(void)
{
    ui_Authenticate = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Authenticate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AttendancePopup1 = lv_obj_create(ui_Authenticate);
    lv_obj_set_width(ui_AttendancePopup1, 280);
    lv_obj_set_height(ui_AttendancePopup1, 180);
    lv_obj_set_align(ui_AttendancePopup1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AttendancePopup1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_AttendancePopup1, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AttendancePopup1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_AttendancePopup1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_AttendancePopup1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_AttendancePopup1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_AttendancePopup1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PopupSuccess1 = lv_label_create(ui_AttendancePopup1);
    lv_obj_set_width(ui_PopupSuccess1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PopupSuccess1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PopupSuccess1, 0);
    lv_obj_set_y(ui_PopupSuccess1, -15);
    lv_obj_set_align(ui_PopupSuccess1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PopupSuccess1, "Authenticate Successfully");
    lv_obj_set_style_text_color(ui_PopupSuccess1, lv_color_hex(0x00A00B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PopupSuccess1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PopupSuccess1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LoadingText = lv_label_create(ui_AttendancePopup1);
    lv_obj_set_width(ui_LoadingText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LoadingText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LoadingText, 0);
    lv_obj_set_y(ui_LoadingText, 15);
    lv_obj_set_align(ui_LoadingText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LoadingText, "Loading to Enroll Screen...");
    lv_obj_set_style_text_color(ui_LoadingText, lv_color_hex(0x00A00B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LoadingText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}
