// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: Popup_Screens

#include "../ui.h"

void ui_Enroll_screen_init(void)
{
    ui_Enroll = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Enroll, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EnrollPopup = lv_obj_create(ui_Enroll);
    lv_obj_set_width(ui_EnrollPopup, 280);
    lv_obj_set_height(ui_EnrollPopup, 180);
    lv_obj_set_align(ui_EnrollPopup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_EnrollPopup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_EnrollPopup, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_EnrollPopup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_EnrollPopup, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_EnrollPopup, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_EnrollPopup, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_EnrollPopup, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StartingEnroll = lv_label_create(ui_EnrollPopup);
    lv_obj_set_width(ui_StartingEnroll, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StartingEnroll, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StartingEnroll, 0);
    lv_obj_set_y(ui_StartingEnroll, -15);
    lv_obj_set_align(ui_StartingEnroll, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StartingEnroll, "Press Authenticate to Enroll");
    lv_obj_set_style_text_color(ui_StartingEnroll, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StartingEnroll, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StartingEnroll, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SelectedID = lv_label_create(ui_EnrollPopup);
    lv_obj_set_width(ui_SelectedID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SelectedID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SelectedID, 0);
    lv_obj_set_y(ui_SelectedID, 15);
    lv_obj_set_align(ui_SelectedID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SelectedID, "Selected ID: ");
    lv_obj_set_style_text_color(ui_SelectedID, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SelectedID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ESCPanel = lv_obj_create(ui_Enroll);
    lv_obj_set_width(ui_ESCPanel, 50);
    lv_obj_set_height(ui_ESCPanel, 20);
    lv_obj_set_x(ui_ESCPanel, -115);
    lv_obj_set_y(ui_ESCPanel, 105);
    lv_obj_set_align(ui_ESCPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ESCPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_ESCPanel, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ESCPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ESCPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ESCPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ESCPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ESCPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ESCButton2 = lv_label_create(ui_ESCPanel);
    lv_obj_set_width(ui_ESCButton2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ESCButton2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ESCButton2, 0);
    lv_obj_set_y(ui_ESCButton2, 1);
    lv_obj_set_align(ui_ESCButton2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ESCButton2, "ESC");
    lv_obj_set_style_text_color(ui_ESCButton2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ESCButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AuthenticatePanel = lv_obj_create(ui_Enroll);
    lv_obj_set_width(ui_AuthenticatePanel, 110);
    lv_obj_set_height(ui_AuthenticatePanel, 20);
    lv_obj_set_x(ui_AuthenticatePanel, 85);
    lv_obj_set_y(ui_AuthenticatePanel, 105);
    lv_obj_set_align(ui_AuthenticatePanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AuthenticatePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_AuthenticatePanel, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AuthenticatePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_AuthenticatePanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_AuthenticatePanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_AuthenticatePanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_AuthenticatePanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AuthenticateButton = lv_label_create(ui_AuthenticatePanel);
    lv_obj_set_width(ui_AuthenticateButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AuthenticateButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AuthenticateButton, 1);
    lv_obj_set_y(ui_AuthenticateButton, 0);
    lv_obj_set_align(ui_AuthenticateButton, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AuthenticateButton, "Authenticate");
    lv_obj_set_style_text_color(ui_AuthenticateButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AuthenticateButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}
