// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: Popup_Screens

#include "../ui.h"

void ui_FingerPopup_screen_init(void)
{
    ui_FingerPopup = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_FingerPopup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AttendancePopup3 = lv_obj_create(ui_FingerPopup);
    lv_obj_set_width(ui_AttendancePopup3, 280);
    lv_obj_set_height(ui_AttendancePopup3, 180);
    lv_obj_set_align(ui_AttendancePopup3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AttendancePopup3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_AttendancePopup3, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AttendancePopup3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_AttendancePopup3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_AttendancePopup3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_AttendancePopup3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_AttendancePopup3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PopupSuccess3 = lv_label_create(ui_AttendancePopup3);
    lv_obj_set_width(ui_PopupSuccess3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PopupSuccess3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PopupSuccess3, 0);
    lv_obj_set_y(ui_PopupSuccess3, -15);
    lv_obj_set_align(ui_PopupSuccess3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PopupSuccess3, "Fingerprint Enroll Successfully");
    lv_obj_set_style_text_color(ui_PopupSuccess3, lv_color_hex(0x00A00B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PopupSuccess3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PopupSuccess3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IDTextFinger = lv_label_create(ui_AttendancePopup3);
    lv_obj_set_width(ui_IDTextFinger, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IDTextFinger, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IDTextFinger, 0);
    lv_obj_set_y(ui_IDTextFinger, 15);
    lv_obj_set_align(ui_IDTextFinger, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IDTextFinger, "ID: ");
    lv_obj_set_style_text_color(ui_IDTextFinger, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IDTextFinger, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}
