// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Home
void ui_Home_screen_init(void);
lv_obj_t * ui_Home;
lv_obj_t * ui_HomeText;
lv_obj_t * ui_POPUPHomePanel;
lv_obj_t * ui_HomeTime;
lv_obj_t * ui_HomeDay;
lv_obj_t * ui_HomeDate;
void ui_event_ButtonHomeToMenu(lv_event_t * e);
lv_obj_t * ui_ButtonHomeToMenu;
// CUSTOM VARIABLES

// SCREEN: ui_Menu
void ui_Menu_screen_init(void);
lv_obj_t * ui_Menu;
lv_obj_t * ui_Menu1;
lv_obj_t * ui_POPUPMenuPanel1;
void ui_event_AttendanceButton(lv_event_t * e);
lv_obj_t * ui_AttendanceButton;
lv_obj_t * ui_Label1;
void ui_event_DataButton(lv_event_t * e);
lv_obj_t * ui_DataButton;
lv_obj_t * ui_Label2;
lv_obj_t * ui_MenuTime;
void ui_event_ButtonMenuToHome(lv_event_t * e);
lv_obj_t * ui_ButtonMenuToHome;
// CUSTOM VARIABLES

// SCREEN: ui_Attendance
void ui_Attendance_screen_init(void);
void ui_event_Attendance(lv_event_t * e);
lv_obj_t * ui_Attendance;
// CUSTOM VARIABLES

// SCREEN: ui_UserData
void ui_UserData_screen_init(void);
lv_obj_t * ui_UserData;
lv_obj_t * ui_Panel4;
void ui_event_UserID1(lv_event_t * e);
lv_obj_t * ui_UserID1;
lv_obj_t * ui_ID1;
lv_obj_t * ui_Name1;
void ui_event_UserID2(lv_event_t * e);
lv_obj_t * ui_UserID2;
lv_obj_t * ui_ID2;
lv_obj_t * ui_Name2;
void ui_event_UserID3(lv_event_t * e);
lv_obj_t * ui_UserID3;
lv_obj_t * ui_ID3;
lv_obj_t * ui_Name3;
void ui_event_UserID4(lv_event_t * e);
lv_obj_t * ui_UserID4;
lv_obj_t * ui_ID4;
lv_obj_t * ui_Name4;
void ui_event_UserID5(lv_event_t * e);
lv_obj_t * ui_UserID5;
lv_obj_t * ui_ID5;
lv_obj_t * ui_Name5;
void ui_event_UserID6(lv_event_t * e);
lv_obj_t * ui_UserID6;
lv_obj_t * ui_ID6;
lv_obj_t * ui_Name6;
void ui_event_UserID7(lv_event_t * e);
lv_obj_t * ui_UserID7;
lv_obj_t * ui_ID7;
lv_obj_t * ui_Name7;
void ui_event_UserID8(lv_event_t * e);
lv_obj_t * ui_UserID8;
lv_obj_t * ui_ID8;
lv_obj_t * ui_Name8;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_IDTextUserData;
lv_obj_t * ui_NameTextUserData;
void ui_event_ESCButton1(lv_event_t * e);
lv_obj_t * ui_ESCButton1;
lv_obj_t * ui_ESCText2;
// CUSTOM VARIABLES

// SCREEN: ui_Authenticate
void ui_Authenticate_screen_init(void);
lv_obj_t * ui_Authenticate;
// CUSTOM VARIABLES

// SCREEN: ui_Enroll
void ui_Enroll_screen_init(void);
void ui_event_Enroll(lv_event_t * e);
lv_obj_t * ui_Enroll;
lv_obj_t * ui_POPUPMenuPanel3;
lv_obj_t * ui_IDTextEnroll;
lv_obj_t * ui_NumberID;
lv_obj_t * ui_IDTextEnroll2;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Finger;
lv_obj_t * ui_FaceID;
lv_obj_t * ui_FingerCheck;
lv_obj_t * ui_FaceIDCheck;
void ui_event_EnrollFingerButton(lv_event_t * e);
lv_obj_t * ui_EnrollFingerButton;
lv_obj_t * ui_Label4;
void ui_event_EnrollFaceIDButton(lv_event_t * e);
lv_obj_t * ui_EnrollFaceIDButton;
lv_obj_t * ui_Label5;
lv_obj_t * ui_UserInfo;
lv_obj_t * ui_EnrollTime;
void ui_event_ESCButton(lv_event_t * e);
lv_obj_t * ui_ESCButton;
lv_obj_t * ui_ESCText;
void ui_event_HomeButton(lv_event_t * e);
lv_obj_t * ui_HomeButton;
lv_obj_t * ui_HomeText1;
// CUSTOM VARIABLES

// SCREEN: ui_FaceIDEnroll
void ui_FaceIDEnroll_screen_init(void);
void ui_event_FaceIDEnroll(lv_event_t * e);
lv_obj_t * ui_FaceIDEnroll;
// CUSTOM VARIABLES

// SCREEN: ui_FingerEnroll
void ui_FingerEnroll_screen_init(void);
lv_obj_t * ui_FingerEnroll;
lv_obj_t * ui_MenuTime2;
lv_obj_t * ui_FP_Enroll;
lv_obj_t * ui_POPUPMenuPanel4;
void ui_event_ESCButton3(lv_event_t * e);
lv_obj_t * ui_ESCButton3;
lv_obj_t * ui_ESCText3;
lv_obj_t * ui_IDTextEnroll3;
lv_obj_t * ui_IDTextEnroll4;
lv_obj_t * ui_IDTextEnroll5;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ButtonHomeToMenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Menu, LV_SCR_LOAD_ANIM_MOVE_LEFT, 50, 0, &ui_Menu_screen_init);
    }
}

void ui_event_AttendanceButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Attendance, LV_SCR_LOAD_ANIM_MOVE_LEFT, 50, 0, &ui_Attendance_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        EVENT_Attendance_Before(e);
    }
}

void ui_event_DataButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        EVENT_Data_List(e);
    }
    // if(event_code == LV_EVENT_CLICKED) {
    //     _ui_screen_change(&ui_UserData, LV_SCR_LOAD_ANIM_MOVE_LEFT, 50, 0, &ui_UserData_screen_init);
    // }
}

void ui_event_ButtonMenuToHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 50, 0, &ui_Home_screen_init);
    }
}

void ui_event_Attendance(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        EVENT_Attendance_After(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 50, 0, &ui_Home_screen_init);
    }
}

void ui_event_UserID1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Enroll, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 50, 0, &ui_Enroll_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        UserIDToEnroll(e);
    }
}

void ui_event_UserID2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Enroll, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 50, 0, &ui_Enroll_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        UserIDToEnroll(e);
    }
}

void ui_event_UserID3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Enroll, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 50, 0, &ui_Enroll_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        UserIDToEnroll(e);
    }
}

void ui_event_UserID4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Enroll, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 50, 0, &ui_Enroll_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        UserIDToEnroll(e);
    }
}

void ui_event_UserID5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Enroll, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 50, 0, &ui_Enroll_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        UserIDToEnroll(e);
    }
}

void ui_event_UserID6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Enroll, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 50, 0, &ui_Enroll_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        UserIDToEnroll(e);
    }
}

void ui_event_UserID7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Enroll, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 50, 0, &ui_Enroll_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        UserIDToEnroll(e);
    }
}

void ui_event_UserID8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Enroll, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 50, 0, &ui_Enroll_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        UserIDToEnroll(e);
    }
}

void ui_event_ESCButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Menu, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 50, 0, &ui_Menu_screen_init);
    }
}

void ui_event_Enroll(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Menu, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 50, 0, &ui_Menu_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        EVENT_Enroll_After(e);
    }
}

void ui_event_EnrollFingerButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_FingerEnroll, LV_SCR_LOAD_ANIM_MOVE_LEFT, 50, 0, &ui_FingerEnroll_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        EVENT_Enroll_Finger_Before(e);
    }
}

void ui_event_EnrollFaceIDButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_FaceIDEnroll, LV_SCR_LOAD_ANIM_MOVE_LEFT, 50, 0, &ui_FaceIDEnroll_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        EVENT_Enroll_FaceID_Before(e);
    }
}

void ui_event_ESCButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        // _ui_screen_change(&ui_UserData, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 50, 0, &ui_UserData_screen_init);
    }
}

void ui_event_HomeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 50, 0, &ui_Home_screen_init);
    }
}

void ui_event_FaceIDEnroll(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Enroll, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 50, 0, &ui_Enroll_screen_init);
    }
}

void ui_event_ESCButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Enroll, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 50, 0, &ui_Enroll_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Home_screen_init();
    ui_Menu_screen_init();
    ui_Attendance_screen_init();
    ui_UserData_screen_init();
    ui_Authenticate_screen_init();
    ui_Enroll_screen_init();
    ui_FaceIDEnroll_screen_init();
    ui_FingerEnroll_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Home);
}
