// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


// SCREEN: ui_Home
void ui_Home_screen_init(void);
void ui_event_Home(lv_event_t * e);
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_HomeText;
extern lv_obj_t * ui_POPUPHomePanel;
// CUSTOM VARIABLES

// SCREEN: ui_Menu
void ui_Menu_screen_init(void);
void ui_event_Menu(lv_event_t * e);
extern lv_obj_t * ui_Menu;
extern lv_obj_t * ui_Menu1;
extern lv_obj_t * ui_POPUPMenuPanel1;
extern lv_obj_t * ui_AttendanceButton;
extern lv_obj_t * ui_Label1;
void ui_event_DataButton(lv_event_t * e);
extern lv_obj_t * ui_DataButton;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

// SCREEN: ui_Attendance
void ui_Attendance_screen_init(void);
extern lv_obj_t * ui_Attendance;
// CUSTOM VARIABLES

// SCREEN: ui_UserData
void ui_UserData_screen_init(void);
extern lv_obj_t * ui_UserData;
// CUSTOM VARIABLES

// SCREEN: ui_Authenticate
void ui_Authenticate_screen_init(void);
extern lv_obj_t * ui_Authenticate;
// CUSTOM VARIABLES

// SCREEN: ui_Enroll
void ui_Enroll_screen_init(void);
extern lv_obj_t * ui_Enroll;
// CUSTOM VARIABLES

// SCREEN: ui_FaceIDEnroll
void ui_FaceIDEnroll_screen_init(void);
extern lv_obj_t * ui_FaceIDEnroll;
// CUSTOM VARIABLES

// SCREEN: ui_FingerEnroll
void ui_FingerEnroll_screen_init(void);
extern lv_obj_t * ui_FingerEnroll;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
