// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void EVENT_Home_Before(lv_event_t * e);
void EVENT_Home_After(lv_event_t * e);
void EVENT_Menu_Before(lv_event_t * e);
void EVENT_Attendance_Before(lv_event_t * e);
void EVENT_Menu_After(lv_event_t * e);
void EVENT_Menu_To_Authenticate(lv_event_t * e);
void EVENT_Attendance_After(lv_event_t * e);
void EVENT_Authenticate_To_Enroll(lv_event_t * e);
void EVENT_Authenticate_After(lv_event_t * e);
void EVENT_Authenticate_Button1(lv_event_t * e);
void EVENT_Authenticate_Button2(lv_event_t * e);
void EVENT_Authenticate_Button5(lv_event_t * e);
void EVENT_Authenticate_Button8(lv_event_t * e);
void EVENT_Authenticate_Button4(lv_event_t * e);
void EVENT_Authenticate_Button7(lv_event_t * e);
void EVENT_Authenticate_Button3(lv_event_t * e);
void EVENT_Authenticate_Button6(lv_event_t * e);
void EVENT_Authenticate_Button9(lv_event_t * e);
void EVENT_Authenticate_DelButton(lv_event_t * e);
void EVENT_Authenticate_EnterButton(lv_event_t * e);
void EVENT_Authenticate_Button0(lv_event_t * e);
void EVENT_Enroll_After(lv_event_t * e);
void EVENT_Enroll_Button1(lv_event_t * e);
void EVENT_Enroll_Button2(lv_event_t * e);
void EVENT_Enroll_Button5(lv_event_t * e);
void EVENT_Enroll_Button8(lv_event_t * e);
void EVENT_Enroll_Button4(lv_event_t * e);
void EVENT_Enroll_Button7(lv_event_t * e);
void EVENT_Enroll_Button3(lv_event_t * e);
void EVENT_Enroll_Button6(lv_event_t * e);
void EVENT_Enroll_Button9(lv_event_t * e);
void EVENT_Enroll_DelButton(lv_event_t * e);
void EVENT_Enroll_EnterButton(lv_event_t * e);
void EVENT_Enroll_Button0(lv_event_t * e);
void EVENT_Enroll_To_UserInfo(lv_event_t * e);
void EVENT_Enroll_Finger(lv_event_t * e);
void EVENT_Enroll_FaceID(lv_event_t * e);
void EVENT_UserInfo_Finger(lv_event_t * e);
void EVENT_UserInfo_FaceID(lv_event_t * e);
void EVENT_UserInfo_Back(lv_event_t * e);
void EVENT_FaceID_Back(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
